import { useState } from 'react';
import { Copy, MoreVertical, Send, Sparkles, ThumbsDown, ThumbsUp } from 'lucide-react';
import { api } from '../api.js';

function ChatbotPanel() {
  const [question, setQuestion] = useState('Which repo had the most commits this month?');
  const [submittedQuestion, setSubmittedQuestion] = useState('Which repo had the most commits this month?');
  const [answer, setAnswer] = useState(
    'Your top synced repository will appear here after the dashboard loads your GitHub activity.'
  );
  const [asking, setAsking] = useState(false);

  async function handleSubmit(event) {
    event.preventDefault();
    const cleanQuestion = question.trim();
    if (!cleanQuestion) return;

    setAsking(true);
    setSubmittedQuestion(cleanQuestion);
    try {
      const result = await api.askChatbot(cleanQuestion);
      setAnswer(result.answer);
    } catch (error) {
      setAnswer('The backend is not connected yet, so the dashboard is showing a polished mock answer for portfolio review.');
    } finally {
      setAsking(false);
    }
  }

  return (
    <article className="card chatbot-card">
      <div className="card-header">
        <div>
          <h2>
            <Sparkles size={20} aria-hidden="true" />
            Ask your GitHub data
          </h2>
        </div>
        <div className="chat-actions">
          <button className="outline-button" type="button">
            New Chat
          </button>
          <button className="icon-button small" type="button" aria-label="More chat actions">
            <MoreVertical size={18} aria-hidden="true" />
          </button>
        </div>
      </div>

      <div className="chat-thread">
        <div className="message-row user-message">
          <div className="message-bubble">
            <p>{submittedQuestion}</p>
            <span>09:15 AM</span>
          </div>
        </div>

        <div className="message-row assistant-message">
          <span className="ai-avatar">AI</span>
          <div className="message-stack">
            <div className="message-bubble">
              <p>{answer}</p>
              <span>09:15 AM</span>
            </div>
            <div className="feedback-actions" aria-label="Message feedback">
              <button type="button" aria-label="Copy response">
                <Copy size={16} aria-hidden="true" />
              </button>
              <button type="button" aria-label="Like response">
                <ThumbsUp size={16} aria-hidden="true" />
              </button>
              <button type="button" aria-label="Dislike response">
                <ThumbsDown size={16} aria-hidden="true" />
              </button>
            </div>
          </div>
        </div>
      </div>

      <form className="chat-form" onSubmit={handleSubmit}>
        <input
          value={question}
          onChange={(event) => setQuestion(event.target.value)}
          aria-label="Ask your GitHub data"
          placeholder="Ask anything about your GitHub data..."
        />
        <button className="primary-icon-button" type="submit" disabled={asking} aria-label="Send question">
          <Send size={18} aria-hidden="true" />
        </button>
      </form>

      <p className="chat-disclaimer">Responses are generated by your configured AI provider and grounded in your data.</p>
    </article>
  );
}

export default ChatbotPanel;
